[frontier]
MODULES = "PrgEnv-cray amd-mixed cray-mpich craype-accel-amd-gfx90a"
MODULE_PATH="/ccs/home/lsawade/Modules/modulefiles"
MODULE_SUFFIX='personal'
PACKAGE_DIR="/lustre/orion/geo111/scratch/lsawade/packages"
COMPILER="CRAY"
GPU="HIP"
USE_INSTALLED_HDF5="" # Define path to HDF5 MODULE. If empty assumes installation
USE_INSTALLED_ADIOS="" # Define path to ADIOS MODULE. If empty assumes installation

[summit]
README='CANT TEST THIS ANYMORE.'
MODULES = "cmake xl spectrum-mpi cuda boost"
MODULE_PATH="/ccs/home/lsawade/Modules/modulefiles"
MODULE_SUFFIX='personal'
PACKAGE_DIR="/scratch/gpfs/lsawade/packages"
COMPILER="IBM"
GPU="HIP"
USE_INSTALLED_HDF5="" # Define path to HDF5 MODULE. If empty assumes installation
USE_INSTALLED_ADIOS="" # Define path to ADIOS MODULE. If empty assumes installation

[traverse]
MODULES="openmpi/gcc/4.0.4/64 cudatoolkit/11.1"
MODULE_PATH="/home/lsawade/Modules/modulefiles"
MODULE_SUFFIX='personal'
PACKAGE_DIR="/scratch/gpfs/lsawade/packages"
COMPILER="GNU"
GPU="CUDA"
USE_INSTALLED_HDF5="" # Define path to HDF5 MODULE. If empty assumes installation
USE_INSTALLED_ADIOS="" # Define path to ADIOS MODULE. If empty assumes installation

[della-gpu]
MODULES="gcc/8 openmpi/gcc/4.1.2 cudatoolkit/11.7"
MODULE_PATH="/home/lsawade/Modules/modulefiles/"
MODULE_SUFFIX='personal'
PACKAGE_DIR="/scratch/gpfs/lsawade/packages"
COMPILER="GNU"
GPU="CUDA"
USE_INSTALLED_HDF5="" # Define path to HDF5 MODULE. If empty assumes installation
USE_INSTALLED_ADIOS="" # Define path to ADIOS MODULE. If empty assumes installation

[personal]
MODULES = ""
MODULE_PATH="/Users/lucassawade/nobackup/modules"
MODULE_SUFFIX='personal'
PACKAGE_DIR="/Users/lucassawade/nobackup/packages"
COMPILER="GNU"
USE_INSTALLED_HDF5="" # Define path to HDF5 MODULE. If empty assumes installation
USE_INSTALLED_ADIOS=""