[frontier]
MODULES = "PrgEnv-cray amd-mixed load cray-mpich craype-accel-amd-gfx90a"
MODULE_PATH="/ccs/home/lsawade/Modules/modulefiles"
PACKAGE_DIR="/lustre/orion/geo111/scratch/lsawade/packages"
COMPILER="CRAY"

[frontier.env]
CUDAWITH="--with-cuda=cuda11"
COMPILER="IBM"

[summit]
README='CANT TEST THIS ANYMORE.'
MODULES = "cmake xl spectrum-mpi cuda boost"
SF_HOST="SUMMIT"
MODULE_PATH="/ccs/home/lsawade/Modules/modulefiles"
PACKAGE_DIR="/scratch/gpfs/lsawade/packages"

[summit.env]
CUDAWITH="--with-cuda=cuda9"
COMPILER="IBM"


[traverse]
MODULES="openmpi/gcc/4.0.4/64 cudatoolkit/11.1"
MODULE_PATH="/home/lsawade/Modules/modulefiles"
PACKAGE_DIR="/scratch/gpfs/lsawade/packages"

[traverse.env]
CUDAWITH="--with-cuda=cuda9"
COMPILER="GNU"

[della-gpu]
MODULES="gcc/8 openmpi/gcc/4.1.2 cudatoolkit/11.7"
MODULE_PATH="/home/lsawade/Modules/modulefiles/"

[della-gpu.env]
CUDAWITH="--with-cuda=cuda11"
COMPILER="GNU"

[ornlhome]
COMPILER="IBM"

